### ISSUE TITLE
WP CLI install script on documentation of mwp-2.0 is invalid

### ISSUE THREAD

**Issue by mattmillerai** [Miller-Media/modern-wordpress#5]
When I try:
wp plugin install https://github.com/Miller-Media/modern-wordpress/raw/master/builds/mwp-framework-stable.zip --activate

As documented, it returns an error of Not Found.

**Comment by kcarwilemiller** [comment]
@MillerMedia Where did you get that link from?

Documentation is here: https://www.codefarma.com/docs/mwp-framework/setup/

Correct link is: https://github.com/codefarma/mwp-framework/raw/master-2.x/builds/mwp-framework-stable.zip

**Comment by kcarwilemiller** [comment]
Oh, I see. You were on the 2.0 branch. That version does not live in this repository any more. I've deleted the branch to eliminate confusion.
